### PR TITLE
Add swipe gesture

### PR DESCRIPTION
**Pull request by eadisor**

### CODE REVIEW

**Comment by Nomsy12** [comment]
Pls update me this is my wife can you pls help me to to see whos chat and texting i know that she have a apps that she having a chatmate

>

**Comment by viktorstrate** [comment]
I don't know what this does or how to test it?

**Comment by akoen** [comment]
Pretty sure this allows swiping between gallery items on mobile

**Comment by viktorstrate** [comment]
@akoen did you test it?

**Comment by Phlogi** [comment]
Can this be integrated please? Really needed feature.

**Pull request merged**
