### PR TITLE
Support Photoview ignore file in user root

### PR DESCRIPTION
**Pull request by Kjeldgaard**
Read .photoviewignore file in user root directory, and excludes
directories which match a .photoviewignore entry.

Signed-off-by: Kjeldgaard <Kjeldgaard@users.noreply.github.com>

### CODE REVIEW

**Comment by Kjeldgaard** [comment]
I did a quick go at the ignore/exclude directories, similar to .gitignore. It is my first Go code, so if it is hopeless, feel free to reject the pull request. However, it seems to work :)

I have 1 issue though, and that is my test directory contains a single album with 34 images, and a few sub directories which should be ignored. The sub directories are ignored as expected. And when I browse "Albums" I get a single album containing all images as expected. But if i browse "Photos", only 12 images are shown... Having said that, I don't think I caused this (famous last works). But have a look, at let me know what you think.

**Comment by viktorstrate** [comment]
Thank you for the pull request. 

It overall looks good, though I haven’t tested it yet - will do later.

How does it work in regards to nested children, for example if I add an ignore file to one folder will it also apply for subfolders?

And also what happens if one folder contains an ignore file, but also contains a child folder with another ignore folder? In that case I imagine the best solution would be to merge the ignore rules.

**Comment by Kjeldgaard** [comment]
> Thank you for the pull request.
> 
> It overall looks good, though I haven’t tested it yet - will do later.
> 
> How does it work in regards to nested children, for example if I add an ignore file to one folder will it also apply for subfolders?
> 
> And also what happens if one folder contains an ignore file, but also contains a child folder with another ignore folder? In that case I imagine the best solution would be to merge the ignore rules.

I'm afraid your expectations are too high :) This is just a basic implementation, though I would expect it covers the majority of the use cases. It looks for a .photoviewignore at user root only and it is dirs which are excluded, not individual files. The reason for this first approach is two-fold, I expect it covers a large majority of the use cases, and I wouldn't spend too much time on it, if my approach was not what you have envisioned.

Nevertheless, I see two obvious extensions for this.
1. It should work on indiviual files as well. This should be straightforward. I'll start with this as soon as time allows.
2. Support .photoviewignore file in subfolders and not only in user root. Here are several routes to take. I'll have to think more about this.

**Comment by viktorstrate** [comment]
> It looks for a .photoviewignore at user root only and it is dirs which are excluded, not individual files.

Ah I see. That might be just fine for v1, but the next major release (see pull-request #137), the way user paths work has been changed to allow each user to have multiple paths, and also users can overlap paths.

This means though, that checking for a single .photoviewignore file at the top level root path might not be a viable solution anymore.
See this https://github.com/photoview/photoview/issues/67#issuecomment-724978779 for a more detailed explaination of the new structure.

> It should work on indiviual files as well.

This would be a fine addition, but I don't necessarily think that it would be critical as I would imagine by far the largest use case for this would be to ignore whole directories.

----

As the v2 branch is soon to be merged into master I think the best solution would be to find a way to integrate this with the v2 branch.

I don't think it would be that hard though, the only real difference important for this is that now in `findAlbumsForUser` the user has an array of root paths instead of just a single one, nearly everything else is the same.

See this snippet from the v2 branch:
https://github.com/photoview/photoview/blob/a10f8ad1ef5a0b4a5dbfd3aa6d9b19d51b42d0d7/api/scanner/scanner_user.go#L29-L32

Maybe a simple solution would be to add a new attribute to the `scanInfo` struct, that holds the ignore rules for that path.
Then each time a new `scanInfo` object is pushed to the `scanQueue` (see below) it should inherit the ignore rules from its parent.
https://github.com/photoview/photoview/blob/a10f8ad1ef5a0b4a5dbfd3aa6d9b19d51b42d0d7/api/scanner/scanner_user.go#L129-L144

If you think that it would be too much to take on or you don't want to, that's fine I can finish it then.

**Comment by Kjeldgaard** [comment]
Sorry for the late reply. I've been busy with family life. I haven't really looked in to V2 yet. I'll be happy to look at a V2 approach for ignoring folders. However, I can't promise any time frame. When I get some time again, I'll see if you have progressed with this issue for V2.

**Comment by viktorstrate** [comment]
No worries. Let me know if you start on the issue, so I can assign it to you.

**Pull request closed without merging**
