### PR TITLE
Update docker-compose.example.yml for Traefik reverse proxy

### PR DESCRIPTION
**Pull request by ftoppi**
Add labels for Traefik reverse proxy, assuming it runs in host network mode

### CODE REVIEW

**Comment by kkovaletp** [comment]
As mentioned in the #863 in Readme changes, I think that this shouldn't be merged into the project, as it creates a false impression that we support the integration with Traefic and should step in in case of some problems with it, while actually from my PoV such external integrations should be outside of the project.

**Comment by viktorstrate** [comment]
Agree with @kkovaletp but it would be nice to add the example to the documentation website here: https://photoview.github.io/en/docs/installation-reverse-proxies/

**Comment by ftoppi** [comment]
Feel free to reject the PR, I just made a suggestion that was fitting in my opinion.

**Comment by kkovaletp** [comment]
Here is the PR to the doc page: https://github.com/photoview/photoview.github.io/pull/26
@viktorstrate - is this what you expect?

**Comment by viktorstrate** [comment]
Yes, I've merged your PR. I'll close this one then ☺️

**Pull request closed without merging**
