### PR TITLE
Fix download path on custom base path

### PR DESCRIPTION
**Pull request by djvaldez**
This is a fix for the incorrect download URL, along the lines of https://github.com/photoview/photoview/pull/838.

### CODE REVIEW

**Comment by kkovaletp** [comment]
I've merged this PR into #910 - a temporary alternative to the master while the project is on hold, so users still could get the latest Photoview improvements and fixes by building an image locally from this PR code

**Review by kkovaletp — APPROVED** [review]

**Comment by jordy2254** [comment]
@djvaldez  Can we have this PR rebased against the branch to ensure the test suite runs correctly, the linked PR broke some tests and a fix has been merged I want to be sure that they don't break again.

**Comment by kkovaletp** [comment]
@jordy2254, as this PR was merged into #910 and all tests are green there, I guess that there is a high probability that they will be green in `master` after merge too, but if you're not sure, you can `git fetch upstream pull/889/head:<new branch name>`, rebase it on master, and run tests - I guess that this will be faster than waiting for the response

**Comment by kkovaletp** [comment]
This is another part of a fix for the #834. Mentioning it here for transparency from the issue perspective

**Comment by jordy2254** [comment]
Given @kkovaletp  has merged this in the past and checked it I'm happy this is ok and shall merge.

**Pull request merged**
