### PR TITLE
Make face detection optional at build-time

### PR DESCRIPTION
**Pull request by emersion**
Add a "no_face_detection" build tag to disable face detection when building. This is useful when installing the face detection dependencies is undesirable and cuts down build times (e.g. on a Raspberry Pi).

### CODE REVIEW

**Comment by emersion** [comment]
Gentle ping

**Comment by emersion** [comment]
Any chance to get this reviewed?

**Comment by kkovaletp** [comment]
I created PR #910 - a temporary alternative to the master while the project is on hold. I like the idea of this PR, however, I see big changes in the source code and I don't see any changes in docker-related files.

Please describe the build procedure in the next cases with your PR:
- building on / for platforms, where face recognition is not supported
- building on / for platforms, where face recognition is supported and should work
- building on / for platforms, where face recognition is supported and should be disabled because the user decided not to use it

I assume that supporting all mentioned cases out of the box will require some changes to the docker-related files, so please implement them as well.

I'm not a developer, so please find a GO developer in our community (you might want to use the project's Discord for that: [https://discord.gg/jQ392948u9](https://discord.gg/jQ392948u9)) to review your PR code when ready.

**Comment by emersion** [comment]
Sorry, I'm interested in neither Docker nor Discord.

**Comment by jordy2254** [comment]
I don't think this is intended for our docker files and won't impact us, anyone using docker that doesn't want to use face detection can do so by setting the environment variable; PHOTOVIEW_DISABLE_FACE_RECOGNITION

This should simply effect those installing manually on low powered devices @emersion  can you clarify this?

I'd need to do some testing on one thing I spotted when I have time but the changes broadly look ok.

**Review by kkovaletp — APPROVED** [review]
Approving the PR from the product level perspective based on the reply from @jordy2254. It is now up to him whether the code is ready to be merged.

**Comment by emersion** [comment]
> This should simply effect those installing manually on low powered devices @emersion can you clarify this?

Yeah. The intent of this PR is to ease compilation on resource-constrained devices: I couldn't compile photoview on a Raspberry Pi without this patch. The behavior is unchanged when compiling without explicitly passing the `no_face_detection` build tag.

(As a side note, I don't enjoy the "product" and "marketing" speak/governance used in photoview. Of course, you are free to run your project however you like - but I'd really prefer to contribute to a community project run by technical people, rather than discussing with product owners or such.)

**Comment by jordy2254** [comment]
@emersion sounds great to me I wa sure that was the case.


Thanks for the feedback on the wording of photoview both @kkovaletp and I are  new to maintaining a project. I'm very technical focussed in background so have the technical skills to review code and ensure changes are sensible. @kkovaletp less so who is more qa focussed in his day to day role.

@emersion I fully agree, I think the problem comes from wording as opposed to anything else. We want to be community driven, and do things the comminity wants which i hope has come across correctly in the discord channel. Maybe create a discussion in the discussions section and you can help us shape the workflow for contributing to photoview and ensure that it remains community focussed.

**Review by jordy2254 — APPROVED** [review]

**Comment by emersion** [comment]
Thanks for taking my feedback into account, appreciated!

**Pull request merged**
