### PR TITLE
Install npm dependencies

### PR DESCRIPTION
**Pull request by benpro**
It is required to run `npm install`.

### CODE REVIEW

**Comment by viktorstrate** [comment]
It should not be necessary to run `npm install graphql`, please see #480.

**Review by viktorstrate — CHANGES_REQUESTED** [review]
It should not be necessary to run `npm install graphql`, please see #480.

**Comment by benpro** [comment]
Right, updated.

**Comment by viktorstrate** [comment]
Thank you, looks good :)

**Pull request merged**
