### PR TITLE
Fix translation error of Chinese UI

### PR DESCRIPTION
**Pull request by WindLi001**
Fix translation error of Chinese UI.  The "detach_image" should be "解除面孔标记", but not "修改面孔命名".

### CODE REVIEW

**Comment by viktorstrate** [comment]
Could you please modify the PR to only contain the change to [zh-CN/translation.json](https://github.com/photoview/photoview/pull/791/files#diff-b42b2d532b3fa8098b1fd19a677058aec22fde3938e618a1e5074a948a42bd56) to keep the changes separate. I have left some comments on your other PR #790 regarding the other changes.

**Comment by WindLi001** [comment]
That's my fault.
I'm not familiar to Git. I commit the 2 changes directly to my master branch, and then I learn that I should make changes on other branches. Then I create this branch to commit the fix of translation, but it's after those 2 changes committed to master branch. And I don't know how to fix it.
I cannot fork another repository from photoview.
I cannot create branch from master before those 2 commits.
Should I reset those 2 commits (and close the pull request of them) on master branch, and create another branch for them?

**Comment by viktorstrate** [comment]
You can add an `upstream` remote and create a branch from the upstream master branch.
See [Working with Forks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-repository-for-a-fork).

```
$ git checkout upstream/master
$ git checkout -b new-feature
```

If it's easier for you to close this pull-request and make a new, that fine :)

**Comment by WindLi001** [comment]
Thank you for your advice. I will study this and have a try.
BTW, the pull request is a very small fix on the translation, so I think it isn't so hurry to be merged in.

**Comment by WindLi001** [comment]
OK, after study I create a new branch and new pull request for fix translation error. And this one will be closed now.

**Pull request closed without merging**
