### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by blakeschafer**
Creating a resource file for any developer who wants to contribute to this open-source project. Adding more details than what was already provided, giving a detailed walkthrough for newcomers on how to make changes in the code.

### CODE REVIEW

**Comment by jordy2254** [comment]
@blakeschafer I've already got a draft somewhere on my machine there's a discussion [here](https://github.com/photoview/photoview/discussions/934) about how we want the contribution flow to look like in the future. However, saying that I will read the contributed doc when I have time and maybe we can use it for the interim. Thanks for your contribution.

**Comment by kkovaletp** [comment]
@blakeschafer, thank you for creating this document!
I think that this is a good start for a discussion. I hope that top contributors will live their feedback here, so we could build the optimal contribution guide for the project.

BTW, it would be great to put a link to this file in the Readme with some short description.
Also, it might be useful to mention our Discord somewhere in the document, so that contributors know that we have it and are open to talk

**Comment by kkovaletp** [comment]
I'd like to add that in case a contributor would like to pick some existing issue up for development, it makes sense to choose from issues with the project assigned (on the right side of the conversation thread) - this means that it was reviewed by maintainer(s) and confirmed to be useful for the project

**Comment by kkovaletp** [comment]
@blakeschafer, also please check the https://github.com/photoview/photoview/discussions/934

**Comment by kkovaletp** [comment]
At the point, where the doc tells about the review of the existing issues, it would be useful to mention that if a contributor sees an issue with useful from his\her PoV feature proposal or a bug, he\she is struggling with, it would be a helpful contribution to like the 1st post of that issue in the conversation tab (the issue description) - in this way, maintainers could know which issues should take the priority.
Of course, if the contributor can also add a comment with some useful info, which might be missing in the issue's thread, that would help as well.

**Comment by blakeschafer** [comment]
Adding a section in the README that links to this document is a great idea! And also, yes I think there should be a link to the discord in the contributing document. Thanks all for the feedback.

**Comment by kkovaletp** [comment]
As there was no activity (new commits) after the feedback was provided, I'd jump into and prepare some commits to implement the ideas from the feedback.
@blakeschafer, I hope that you don't mind) Let me know if you'd prefer to cover it by yourself and going to provide updates soon - then I'll step back and let you finish the job)

**Comment by kkovaletp** [comment]
> I've already got a draft somewhere on my machine

@jordy2254, can you please share the draft, so I can use it as a source while preparing this PR?
I'll read the comments here and the discussion #934 to refresh my understanding and the ideas proposed

**Comment by kkovaletp** [comment]
@jordy2254, I've committed the changes to address the feedback here and in the discussion #934, as well as merged your template from that discussion.
Please review this PR and let me know whether we need to add\change\remove something, or if we're good to go with it as our 1st version of the guide, improving it later according to some future changes in our processes (if any).

**Comment by blakeschafer** [comment]
Thanks, Jordy, I made this pr for a class, and for my final project am using it to hopefully get this pr merged into the main branch. So I can definitely finish it here in the next couple of weeks. Thanks for your work!

**Comment by kkovaletp** [comment]
> I can definitely finish it here in the next couple of weeks

Thanks, @blakeschafer, but as far as I see, I've done the pending changes implementation, so, unless @jordy2254 asks for some additional changes, there is nothing to do)

**Comment by kkovaletp** [comment]
@jordy2254, good point. However, I never setup a development environment and use eiser local docker build and/or GitHub Actions to test my changes.
So, we'd rely on you or somebody else to contribute these improvements to the Contributing guide.

Do you think that we could merge the current version and add the mentioned improvements later, or you'd prefer to wait with the merge until they are implemented in this PR?

**Comment by googollee** [comment]
@kkovaletp I read the doc and it looks good to me to submit.

@jordy2254 I'd like to work on the doc about setting the developing environment in another PR.

**Review by googollee — APPROVED** [review]
LGTM

**Pull request merged**
