### PR TITLE
Display Version Number on WebUI

### PR DESCRIPTION
**Pull request by robin-moser**
The issue #321 was a great idea, so I tried implementing it.

The Settings page gets a new section which displays the version number as well as the build date.
These two variables get already populated in the CI build process.

> Photoview Version Info

Do you think, it would also make sense to include the latest Git commit-sha, when building with Github Actions?
 
Comments are welcome!

solves #321

### CODE REVIEW

**Comment by viktorstrate** [comment]
Awesome, looks great!
I like your idea of adding the git commit hash as well, it could be also be a link to the github commit, eg.
`https://github.com/photoview/photoview/commit/98c1722dcf5e93c7c8a79cee607b14e5461fe3b4`

Maybe something like this, similar to the way github shows hashes (98c1722dcf5e93c7c8a79cee607b14e5461fe3b4):

```html
<a href="https://github.com/photoview/photoview/commit/98c1722dcf5e93c7c8a79cee607b14e5461fe3b4" title="98c1722dcf5e93c7c8a79cee607b14e5461fe3b4">
  98c1722
</a>

**Comment by robin-moser** [comment]
> Maybe something like this, similar to the way github shows hashes

Great idea, I just implemented it, here's a new screenshot:

> Bildschirmfoto 2021-04-20 um 18 18 38

**Comment by viktorstrate** [comment]
Looks good 👌

**Comment by viktorstrate** [comment]
@robin-moser just pushed it to the demo server, looks good :)

**Comment by robin-moser** [comment]
Great, thanks for merging :)

**Pull request merged**
