### PR TITLE
Add support for GIF images

### PR DESCRIPTION
**Pull request by Jorilx**
Patch to add support for GIF images.
I've tested it using the Docker development environment, please tell me if I'm missing something.
Thanks!

### CODE REVIEW

**Comment by kkovaletp** [comment]
@Jorilx, thanks for your PR. We're going to implement the media type autodetect feature instead of the current dictionary-based approach. But until then we could add this improvement if it is ok from the code perspective. @googollee, what do you think?

**Comment by googollee** [comment]
The code is OK. But, does an GIF count as a photo?

@Jorilx Could you describe more about your case here? Do you have a gallary of GIFs? Still or motional?

**Comment by kkovaletp** [comment]
@googollee, while we're waiting for the answer from @Jorilx, I'd like to share my opinion:
- GIF is also a picture. While it is not common to use this format for photos, technically we could support it
- As far as I know, some phones can create motion photos in GIF format
- Once we have the media type autodetect functionality, I expect GIF to be supported automatically by ImageMagick, so there will be no functionality downgrade if we merge it now
- According to the current release plan, the media autodetect feature is going to be included in the next release, so even if we merge this PR, it will be overwritten later by the new code and stay only in the list of changes in the version description, but with no real impact on users, who don't pull the `master` branch/image.

**Comment by Jorilx** [comment]
> @Jorilx Could you describe more about your case here? Do you have a gallary of GIFs? Still or motional?

Yes, I have a gallery of GIFs (comic strips, actually)

**Review by googollee — COMMENTED** [review]
LGTM

**Review by googollee — APPROVED** [review]
LGTM

**Comment by googollee** [comment]
I hope to know the use case. @Jorilx, thanks for sharing.

**Comment by Jorilx** [comment]
Thanks for the quick merge! :)

**Pull request merged**
