### PR TITLE
Check lazy load on scroll in PhotoGallery view

### PR DESCRIPTION
**Pull request by andrasmaroy**
My attempt at fixing #149.

I'm no frontend expert, but this seems to fix the issue for me.

### CODE REVIEW

**Comment by viktorstrate** [comment]
Thank you for the pull request. Correct me if i'm wrong, but doesn't [react-lazyload](https://github.com/twobin/react-lazyload) already do this?

With my experience this problem doesn't happen when scrolling, only sometimes when resizing the window, or when there are too few photos on the page to being able to scroll.

Can you think of a way where I can test this reliably? In what case(s) did you experience the bug where this change fixed it?

**Comment by andrasmaroy** [comment]
I encountered this issue when opening a shared album in a window that didn't fit all the photos. The photos that fit in the beginning loaded correctly, the rest stayed grey as reported in the issue.

Tested in safari and firefox, both reproduced the issue.

**Comment by viktorstrate** [comment]
Okay thank you. I will investigate it further.
I would like if we could fix this without adding another scroll listener, as I think it could hurt performance, but this info is a good starting point.

**Comment by viktorstrate** [comment]
I found a layout issue with album shares, and it also solved the lazy load problem.
See my fix in commit fa35ea1.

I will close the original issue aswell, but if it still isn't fixed please write a comment in the issue and I will open it again.
Thank you for providing the steps to reproduce, and for taking the time to attempt a fix.

**Comment by andrasmaroy** [comment]
Looking good, thanks for fixing it properly :)

Np, I know how hard things are to fix without knowing how to repro.

**Pull request closed without merging**
