### PR TITLE
Create a Development dockerfile

### PR DESCRIPTION
**Pull request by gwynm**
Modelled on the Production dockerfile, but simplifies the build process.
We mount the source code from the host machine and build it, then run
the servers in development mode, using Air to get live-reloading in Go.

Test photos are from thiscatdoesnotexist.com.

### CODE REVIEW

**Comment by viktorstrate** [comment]
Sorry for the late reply

I get the following error when running the docker-compose file, after `air` tries to build the go binary:

```
photoview_1  | building...
photoview_1  | # runtime/cgo
photoview_1  | cgo: C compiler "aarch64-linux-gnu-gcc" not found: exec: "aarch64-linux-gnu-gcc": executable file not found in $PATH
photoview_1  | failed to build, error: exit status 2
```

I'm using an intel macbook. I've tried both with and without `TARGETPLATFORM='linux/arm64'`.

Could have something to do with this line in the Dockerfile?

```dockerfile
ENV COMPILER_ARCH aarch64-linux-gnu
```

The UI loads as expected though.

**Comment by gwynm** [comment]
> Sorry for the late reply
> 
> I get the following error when running the docker-compose file, after `air` tries to build the go binary:
> 
> ```
> photoview_1  | building...
> photoview_1  | # runtime/cgo
> photoview_1  | cgo: C compiler "aarch64-linux-gnu-gcc" not found: exec: "aarch64-linux-gnu-gcc": executable file not found in $PATH
> photoview_1  | failed to build, error: exit status 2
> ```
> 
> I'm using an intel macbook. I've tried both with and without `TARGETPLATFORM='linux/arm64'`.
> 
> Could have something to do with this line in the Dockerfile?
> 
> ```dockerfile
> ENV COMPILER_ARCH aarch64-linux-gnu
> ```
> 
> The UI loads as expected though.

Aha, yeah, I haven't tried this on intel. I didn't fully understand the cross-compiling setup, so I've probably broken something in this. I'll fish out an intel machine and have a look when I get a chance.

**Comment by googollee** [comment]
FYI, I tried to do the similar thing with https://github.com/photoview/photoview/pull/986 but I dropped it as fs notifying doesn't work on macOS with Docker containers.

Now I'm working on https://github.com/photoview/photoview/pull/995 to update the set up session in README.md for developing locally.

**Comment by googollee** [comment]
https://github.com/photoview/photoview/pull/997 documents how to use Docker to set up development environment. I think it's the same as this PR. 

@gwynm do you have time to review https://github.com/photoview/photoview/pull/997?

**Comment by kkovaletp** [comment]
An alternative solution was implemented by #1003. Closing this PR.
But anyway, thanks for your contribution.

**Pull request closed without merging**
